remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Familie Sowade & Probst
description: Herzlich willkommen auf der kleinen Homepage unserer Familie.
github:
  is_project_page: false
